import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import ConvexClientProvider from "./ConvexClientProvider";
import Footer from "./footer";
import { Header } from "./header";
import Transition from "./transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FileDrive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <NextTopLoader showSpinner={false} />
          <Header />
          <Transition>{children}</Transition>
          <Footer />
          <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
